/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WRITE = 9;
  /** RegularExpression Id. */
  int READ = 10;
  /** RegularExpression Id. */
  int THIS = 11;
  /** RegularExpression Id. */
  int DO = 12;
  /** RegularExpression Id. */
  int BODY = 13;
  /** RegularExpression Id. */
  int DESCRIPTION = 14;
  /** RegularExpression Id. */
  int DECLARATION = 15;
  /** RegularExpression Id. */
  int DESIGNATE = 16;
  /** RegularExpression Id. */
  int AVALIATE = 17;
  /** RegularExpression Id. */
  int REPEAT = 18;
  /** RegularExpression Id. */
  int CONSTANT = 19;
  /** RegularExpression Id. */
  int VARIABLE = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int AS = 22;
  /** RegularExpression Id. */
  int OPLUS = 23;
  /** RegularExpression Id. */
  int OMINUS = 24;
  /** RegularExpression Id. */
  int OMULTIPLY = 25;
  /** RegularExpression Id. */
  int OPOWER = 26;
  /** RegularExpression Id. */
  int ODIV = 27;
  /** RegularExpression Id. */
  int OMOD = 28;
  /** RegularExpression Id. */
  int OEQ = 29;
  /** RegularExpression Id. */
  int ODEQ = 30;
  /** RegularExpression Id. */
  int ONEQ = 31;
  /** RegularExpression Id. */
  int OLT = 32;
  /** RegularExpression Id. */
  int OGT = 33;
  /** RegularExpression Id. */
  int OLTE = 34;
  /** RegularExpression Id. */
  int OGTE = 35;
  /** RegularExpression Id. */
  int OAND = 36;
  /** RegularExpression Id. */
  int OOR = 37;
  /** RegularExpression Id. */
  int ONOT = 38;
  /** RegularExpression Id. */
  int TYPE = 39;
  /** RegularExpression Id. */
  int IS = 40;
  /** RegularExpression Id. */
  int OCBRACKETS = 41;
  /** RegularExpression Id. */
  int CCBRACKETS = 42;
  /** RegularExpression Id. */
  int OBRACKETS = 43;
  /** RegularExpression Id. */
  int CBRACKETS = 44;
  /** RegularExpression Id. */
  int OPARENTHESES = 45;
  /** RegularExpression Id. */
  int CPARENTHESES = 46;
  /** RegularExpression Id. */
  int TRUE = 47;
  /** RegularExpression Id. */
  int UNTRUE = 48;
  /** RegularExpression Id. */
  int FALSE = 49;
  /** RegularExpression Id. */
  int RESULT = 50;
  /** RegularExpression Id. */
  int SLASH = 51;
  /** RegularExpression Id. */
  int DOT = 52;
  /** RegularExpression Id. */
  int COMMA = 53;
  /** RegularExpression Id. */
  int ALL = 54;
  /** RegularExpression Id. */
  int ALL_TYPES = 55;
  /** RegularExpression Id. */
  int NUM = 56;
  /** RegularExpression Id. */
  int ID = 57;
  /** RegularExpression Id. */
  int INT = 58;
  /** RegularExpression Id. */
  int REAL = 59;
  /** RegularExpression Id. */
  int STRING = 60;
  /** RegularExpression Id. */
  int LOGIC = 61;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_BLOCK_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"write\"",
    "\"read\"",
    "\"this\"",
    "\"do\"",
    "\"body\"",
    "\"description\"",
    "\"declaration\"",
    "\"designate\"",
    "\"avaliate\"",
    "\"repeat\"",
    "\"constant\"",
    "\"variable\"",
    "\"and\"",
    "\"as\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"**\"",
    "\"%\"",
    "\"%%\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<<\"",
    "\">>\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"type\"",
    "\"is\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"true\"",
    "\"untrue\"",
    "\"false\"",
    "\"result\"",
    "\"/\"",
    "\".\"",
    "\",\"",
    "\"all\"",
    "<ALL_TYPES>",
    "<NUM>",
    "<ID>",
    "<INT>",
    "<REAL>",
    "<STRING>",
    "<LOGIC>",
  };

}
