/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WRITE = 5;
  /** RegularExpression Id. */
  int READ = 6;
  /** RegularExpression Id. */
  int THIS = 7;
  /** RegularExpression Id. */
  int DO = 8;
  /** RegularExpression Id. */
  int BODY = 9;
  /** RegularExpression Id. */
  int DESCRIPTION = 10;
  /** RegularExpression Id. */
  int DECLARATION = 11;
  /** RegularExpression Id. */
  int DESIGNATE = 12;
  /** RegularExpression Id. */
  int AVALIATE = 13;
  /** RegularExpression Id. */
  int REPEAT = 14;
  /** RegularExpression Id. */
  int CONSTANT = 15;
  /** RegularExpression Id. */
  int VARIABLE = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int AS = 19;
  /** RegularExpression Id. */
  int OPLUS = 20;
  /** RegularExpression Id. */
  int OMINUS = 21;
  /** RegularExpression Id. */
  int OMULTIPLY = 22;
  /** RegularExpression Id. */
  int OPOWER = 23;
  /** RegularExpression Id. */
  int ODIV = 24;
  /** RegularExpression Id. */
  int OMOD = 25;
  /** RegularExpression Id. */
  int OEQ = 26;
  /** RegularExpression Id. */
  int ODEQ = 27;
  /** RegularExpression Id. */
  int ONEQ = 28;
  /** RegularExpression Id. */
  int OLT = 29;
  /** RegularExpression Id. */
  int OGT = 30;
  /** RegularExpression Id. */
  int OLTE = 31;
  /** RegularExpression Id. */
  int OGTE = 32;
  /** RegularExpression Id. */
  int OAND = 33;
  /** RegularExpression Id. */
  int OOR = 34;
  /** RegularExpression Id. */
  int ONOT = 35;
  /** RegularExpression Id. */
  int TYPE = 36;
  /** RegularExpression Id. */
  int IS = 37;
  /** RegularExpression Id. */
  int OCBRACKETS = 38;
  /** RegularExpression Id. */
  int CCBRACKETS = 39;
  /** RegularExpression Id. */
  int OBRACKETS = 40;
  /** RegularExpression Id. */
  int CBRACKETS = 41;
  /** RegularExpression Id. */
  int OPARENTHESES = 42;
  /** RegularExpression Id. */
  int CPARENTHESES = 43;
  /** RegularExpression Id. */
  int TRUE = 44;
  /** RegularExpression Id. */
  int UNTRUE = 45;
  /** RegularExpression Id. */
  int FALSE = 46;
  /** RegularExpression Id. */
  int RESULT = 47;
  /** RegularExpression Id. */
  int SLASH = 48;
  /** RegularExpression Id. */
  int DOT = 49;
  /** RegularExpression Id. */
  int COMMA = 50;
  /** RegularExpression Id. */
  int ALL = 51;
  /** RegularExpression Id. */
  int ALL_TYPES = 52;
  /** RegularExpression Id. */
  int NUM = 53;
  /** RegularExpression Id. */
  int ID = 54;
  /** RegularExpression Id. */
  int INT = 55;
  /** RegularExpression Id. */
  int REAL = 56;
  /** RegularExpression Id. */
  int STRING = 57;
  /** RegularExpression Id. */
  int LOGIC = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"write\"",
    "\"read\"",
    "\"this\"",
    "\"do\"",
    "\"body\"",
    "\"description\"",
    "\"declaration\"",
    "\"designate\"",
    "\"avaliate\"",
    "\"repeat\"",
    "\"constant\"",
    "\"variable\"",
    "\"and\"",
    "\"or\"",
    "\"as\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"**\"",
    "\"%\"",
    "\"%%\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<<\"",
    "\">>\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"type\"",
    "\"is\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"true\"",
    "\"untrue\"",
    "\"false\"",
    "\"result\"",
    "\"/\"",
    "\".\"",
    "\",\"",
    "\"all\"",
    "<ALL_TYPES>",
    "<NUM>",
    "<ID>",
    "<INT>",
    "<REAL>",
    "<STRING>",
    "<LOGIC>",
  };

}
