/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WRITE = 5;
  /** RegularExpression Id. */
  int READ = 6;
  /** RegularExpression Id. */
  int THIS = 7;
  /** RegularExpression Id. */
  int DO = 8;
  /** RegularExpression Id. */
  int BODY = 9;
  /** RegularExpression Id. */
  int DESCRIPTION = 10;
  /** RegularExpression Id. */
  int DECLARATION = 11;
  /** RegularExpression Id. */
  int DESIGNATE = 12;
  /** RegularExpression Id. */
  int AVALIATE = 13;
  /** RegularExpression Id. */
  int REPEAT = 14;
  /** RegularExpression Id. */
  int CONSTANT = 15;
  /** RegularExpression Id. */
  int VARIABLE = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int AS = 18;
  /** RegularExpression Id. */
  int EQ = 19;
  /** RegularExpression Id. */
  int TYPE = 20;
  /** RegularExpression Id. */
  int IS = 21;
  /** RegularExpression Id. */
  int OCBRACKETS = 22;
  /** RegularExpression Id. */
  int CCBRACKETS = 23;
  /** RegularExpression Id. */
  int OBRACKETS = 24;
  /** RegularExpression Id. */
  int CBRACKETS = 25;
  /** RegularExpression Id. */
  int OPARENTHESES = 26;
  /** RegularExpression Id. */
  int CPARENTHESES = 27;
  /** RegularExpression Id. */
  int TRUE = 28;
  /** RegularExpression Id. */
  int UNTRUE = 29;
  /** RegularExpression Id. */
  int FALSE = 30;
  /** RegularExpression Id. */
  int RESULT = 31;
  /** RegularExpression Id. */
  int SLASH = 32;
  /** RegularExpression Id. */
  int DOT = 33;
  /** RegularExpression Id. */
  int COMMA = 34;
  /** RegularExpression Id. */
  int ALL = 35;
  /** RegularExpression Id. */
  int ALL_TYPES = 36;
  /** RegularExpression Id. */
  int NUM = 37;
  /** RegularExpression Id. */
  int ID = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"write\"",
    "\"read\"",
    "\"this\"",
    "\"do\"",
    "\"body\"",
    "\"description\"",
    "\"declaration\"",
    "\"designate\"",
    "\"avaliate\"",
    "\"repeat\"",
    "\"constant\"",
    "\"variable\"",
    "\"and\"",
    "\"as\"",
    "\"=\"",
    "\"type\"",
    "\"is\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"true\"",
    "\"untrue\"",
    "\"false\"",
    "\"result\"",
    "\"/\"",
    "\".\"",
    "\",\"",
    "\"all\"",
    "<ALL_TYPES>",
    "<NUM>",
    "<ID>",
  };

}
